# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectDevice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #FFFFFF;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblHeadband = QtWidgets.QLabel(self.centralwidget)
        self.lblHeadband.setGeometry(QtCore.QRect(280, 40, 211, 171))
        self.lblHeadband.setText("")
        self.lblHeadband.setPixmap(QtGui.QPixmap('media/muse headband.jpg'))
        self.lblHeadband.setScaledContents(True)
        self.lblHeadband.setObjectName("lblHeadband")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(220, 320, 171, 41))
        self.btnConnect.setStyleSheet("QPushButton {\n"
"    background-color: #C5D8FF;\n"
"    color: #000000;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #AFC6FF;\n"
"}")
        self.btnConnect.setObjectName("btnConnect")
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(220, 400, 311, 31))
        self.lblStatus.setStyleSheet("color: #4C42D7;\n"
"font-weight: bold;")
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(220, 230, 349, 69))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblConnectTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblConnectTitle.setFont(font)
        self.lblConnectTitle.setStyleSheet("color: #4C42D7;\n"
"")
        self.lblConnectTitle.setObjectName("lblConnectTitle")
        self.verticalLayout.addWidget(self.lblConnectTitle)
        self.lblInstruction = QtWidgets.QLabel(self.widget)
        self.lblInstruction.setStyleSheet("color: #555555;\n"
"font-size: 12px;")
        self.lblInstruction.setObjectName("lblInstruction")
        self.verticalLayout.addWidget(self.lblInstruction)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnConnect.setText(_translate("MainWindow", "“CONNECT”"))
        self.lblConnectTitle.setText(_translate("MainWindow", "\"Connect Device\""))
        self.lblInstruction.setText(_translate("MainWindow", "“Click the power button on your MUSE 2\n"
"Make sure Bluetooth is ON”"))
